# Jekyll configuration to serve static files
title: "AI Research Paper Discovery"
description: "Live demo of vector similarity search engine"
baseurl: ""
url: "https://manan23-dev.github.io"

# Disable Jekyll processing
plugins: []
markdown: kramdown
highlighter: rouge

# Exclude everything except what we want
exclude:
  - README.md.backup
  - RENDER_DEPLOYMENT.md
  - tests/
  - src/
  - main.py
  - requirements.txt
  - Dockerfile
  - docker-compose.yml
  - docker-deploy.sh
  - nginx.conf
  - .dockerignore
  - .gitignore
  - app.html

# Include only what we need
include:
  - assets/
  - index.html
  - .nojekyll
