apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vector-search
  template:
    metadata:
      labels:
        app: vector-search
    spec:
      containers:
      - name: vector-search
        image: vector-search:latest
        ports:
        - containerPort: 8000
